### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by cahyoari89** [UNL-CCFL/jawoot#3]
how to solve
Error: connect ECONNREFUSED 127.0.0.1:5432

thanks

**Comment by jshrc** [comment]
Make sure you've started the server with 

`node server/server.js`

and make sure you don't have a firewall running on your machine that would be blocking incoming connections to that port.

**Comment by jshrc** [comment]
I think I figured it out. in src/js/app.js the API and socket ports are still hardcoded :( If you manually change those to your correct ports and run `npm run dev` or `npm run prod` to rebuild it might work. 

I'll get the build updated to grab those from .env. Sorry about this!

**Comment by rjadr** [comment]
I tried to solve it this way in my fork, but it appears not to be the issue. 5432 is the PostgreSQL port, but I'm trying to use mysql. Is knex somehow defaulting to PostgreSQL?

**Comment by jshrc** [comment]
@cahyoari89 The latest commit should fix your issue

@rjadr If you're seeing the same thing as OP the latest commit should work as well. It'll build with the .env vars into the frontend app now. Sorry about that!
